/* Generated by re2c 0.13.5 on Sat Apr 13 05:16:28 2013 */
#line 1 "scanner.re"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <fcntl.h>

#include "scanner.h"

typedef unsigned int uint;
typedef unsigned char uchar;

#define BSIZE   4096

#define YYCTYPE     uchar
#define YYCURSOR    cursor
#define YYLIMIT     s->lim
#define YYMARKER    s->ptr
#define YYFILL(n)   {cursor = fill(s, cursor);}

#define RET(i)  {tokenid = i; goto retpoint;}

static
uchar *fill(Scanner *s, uchar *cursor){
    if(!s->eof) {
        uint cnt = s->tok - s->bot;
        if(cnt){
            memcpy(s->bot, s->tok, s->lim - s->tok);
            s->tok = s->bot;
            s->ptr -= cnt;
            cursor -= cnt;
            s->pos -= cnt;
            s->lim -= cnt;
        }
        if((s->top - s->lim) < BSIZE){
            uchar *buf = (uchar*) malloc(((s->lim - s->bot) + BSIZE)*sizeof(uchar));
            memcpy(buf, s->tok, s->lim - s->tok);
            s->tok = buf;
            s->ptr = &buf[s->ptr - s->bot];
            cursor = &buf[cursor - s->bot];
            s->pos = &buf[s->pos - s->bot];
            s->lim = &buf[s->lim - s->bot];
            s->top = &s->lim[BSIZE];
            free(s->bot);
            s->bot = buf;
        }
		if((cnt = fread(s->lim, 1, BSIZE, s->file)) != BSIZE){
        /*if((cnt = read(s->fd, (char*) s->lim, BSIZE)) != BSIZE){*/
            s->eof = &s->lim[cnt]; *(s->eof)++ = '\n';
        }
        s->lim += cnt;
    }
    return cursor;
}

unsigned scan(Scanner *s, SourceLocation *loc){
    uchar *cursor = s->cur;
    unsigned tokenid;
    unsigned int first_line, first_column;
    
std:
    first_line = s->line;
    s->tok = cursor;
    first_column = 1 + (unsigned int)(s->tok - s->pos);
#line 75 "scanner.re"



#line 70 "scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if ((YYLIMIT - YYCURSOR) < 13) YYFILL(13);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy79;
	case '\n':	goto yy81;
	case '!':	goto yy73;
	case '"':	goto yy35;
	case '#':	goto yy77;
	case '$':	goto yy75;
	case '%':	goto yy47;
	case '&':	goto yy30;
	case '\'':
	case ';':	goto yy4;
	case '(':	goto yy65;
	case ')':	goto yy67;
	case '*':	goto yy45;
	case '+':	goto yy41;
	case ',':	goto yy59;
	case '-':	goto yy43;
	case '.':	goto yy33;
	case '/':	goto yy2;
	case '0':	goto yy28;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy32;
	case ':':	goto yy61;
	case '<':	goto yy39;
	case '=':	goto yy63;
	case '>':	goto yy37;
	case '@':	goto yy26;
	case 'A':
	case 'a':	goto yy15;
	case 'B':
	case 'H':
	case 'K':
	case 'M':
	case 'O':
	case 'Q':
	case 'V':
	case 'X':
	case 'Y':
	case 'Z':
	case 'b':
	case 'h':
	case 'k':
	case 'm':
	case 'o':
	case 'q':
	case 'v':
	case 'x':
	case 'y':
	case 'z':	goto yy25;
	case 'C':
	case 'c':	goto yy13;
	case 'D':
	case 'd':	goto yy14;
	case 'E':
	case 'e':	goto yy18;
	case 'F':
	case 'f':	goto yy20;
	case 'G':
	case 'g':	goto yy11;
	case 'I':
	case 'i':	goto yy19;
	case 'J':
	case 'j':	goto yy12;
	case 'L':
	case 'l':	goto yy10;
	case 'N':
	case 'n':	goto yy21;
	case 'P':
	case 'p':	goto yy24;
	case 'R':
	case 'r':	goto yy6;
	case 'S':
	case 's':	goto yy16;
	case 'T':
	case 't':	goto yy17;
	case 'U':
	case 'u':	goto yy23;
	case 'W':
	case 'w':	goto yy22;
	case '[':	goto yy69;
	case ']':	goto yy71;
	case '^':	goto yy49;
	case '_':	goto yy8;
	case '{':	goto yy55;
	case '|':	goto yy51;
	case '}':	goto yy57;
	case '~':	goto yy53;
	default:	goto yy83;
	}
yy2:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '*':	goto yy365;
	case '=':	goto yy363;
	default:	goto yy3;
	}
yy3:
#line 214 "scanner.re"
	{ RET('/'); }
#line 186 "scanner.c"
yy4:
	++YYCURSOR;
#line 79 "scanner.re"
	{ goto linecomment; }
#line 191 "scanner.c"
yy6:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'E':
	case 'e':	goto yy355;
	default:	goto yy170;
	}
yy7:
#line 153 "scanner.re"
	{
        if (commands_get_from_range(
            (const char *)s->tok,
            (const char *)cursor)) {
            
            RET(COMMAND)
        } else {
            RET(ID)
        }
    }
#line 211 "scanner.c"
yy8:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case ' ':
	case '\'':
	case ';':	goto yy350;
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy9;
	}
yy9:
#line 145 "scanner.re"
	{
        printf("%s:%d:%d: warning: identifier _ is invalid"
            " (it is used for line continuation)\n",
            s->filename, first_line, first_column);
        goto std;
    }
#line 298 "scanner.c"
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy339;
	case 'E':
	case 'e':	goto yy340;
	default:	goto yy170;
	}
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy331;
	default:	goto yy170;
	}
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy327;
	default:	goto yy170;
	}
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy315;
	case 'O':
	case 'o':	goto yy316;
	default:	goto yy170;
	}
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy291;
	case 'I':
	case 'i':	goto yy292;
	case 'O':
	case 'o':	goto yy293;
	default:	goto yy170;
	}
yy15:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy274;
	case 'S':
	case 's':	goto yy275;
	case 'U':
	case 'u':	goto yy277;
	default:	goto yy170;
	}
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy257;
	case 'T':
	case 't':	goto yy258;
	case 'U':
	case 'u':	goto yy259;
	default:	goto yy170;
	}
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy247;
	case 'O':
	case 'o':	goto yy248;
	case 'Y':
	case 'y':	goto yy250;
	default:	goto yy170;
	}
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy219;
	case 'N':
	case 'n':	goto yy220;
	default:	goto yy170;
	}
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy217;
	default:	goto yy170;
	}
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy214;
	default:	goto yy170;
	}
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy208;
	default:	goto yy170;
	}
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy194;
	case 'H':
	case 'h':	goto yy195;
	default:	goto yy170;
	}
yy23:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy177;
	case 'S':
	case 's':	goto yy178;
	default:	goto yy170;
	}
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy172;
	default:	goto yy170;
	}
yy25:
	yych = *++YYCURSOR;
	goto yy170;
yy26:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy168;
yy27:
#line 164 "scanner.re"
	{ RET(SYSVAR); }
#line 440 "scanner.c"
yy28:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'X':
	case 'x':	goto yy164;
	default:	goto yy141;
	}
yy29:
#line 166 "scanner.re"
	{ RET(INTCONST); }
#line 452 "scanner.c"
yy30:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '=':	goto yy162;
	case 'H':
	case 'h':	goto yy164;
	default:	goto yy31;
	}
yy31:
#line 209 "scanner.re"
	{ RET('&'); }
#line 465 "scanner.c"
yy32:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy141;
yy33:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':	goto yy127;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy128;
	default:	goto yy34;
	}
yy34:
#line 208 "scanner.re"
	{ RET('.'); }
#line 490 "scanner.c"
yy35:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy36;
	default:	goto yy123;
	}
yy36:
#line 234 "scanner.re"
	{
        printf("%s:%d:%d: warning: unexpected character %c (0x%02X)\n",
            s->filename, first_line, first_column, *s->tok, *s->tok);
        goto std;
    }
#line 505 "scanner.c"
yy37:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy116;
	case '>':	goto yy118;
	default:	goto yy38;
	}
yy38:
#line 217 "scanner.re"
	{ RET('>'); }
#line 516 "scanner.c"
yy39:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '<':	goto yy112;
	case '=':	goto yy110;
	case '>':	goto yy108;
	default:	goto yy40;
	}
yy40:
#line 216 "scanner.re"
	{ RET('<'); }
#line 528 "scanner.c"
yy41:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '+':	goto yy104;
	case '=':	goto yy106;
	default:	goto yy42;
	}
yy42:
#line 212 "scanner.re"
	{ RET('+'); }
#line 539 "scanner.c"
yy43:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '-':	goto yy100;
	case '=':	goto yy102;
	case '>':	goto yy98;
	default:	goto yy44;
	}
yy44:
#line 211 "scanner.re"
	{ RET('-'); }
#line 551 "scanner.c"
yy45:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy96;
	default:	goto yy46;
	}
yy46:
#line 213 "scanner.re"
	{ RET('*'); }
#line 561 "scanner.c"
yy47:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy94;
	default:	goto yy48;
	}
yy48:
#line 215 "scanner.re"
	{ RET('%'); }
#line 571 "scanner.c"
yy49:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy92;
	default:	goto yy50;
	}
yy50:
#line 218 "scanner.re"
	{ RET('^'); }
#line 581 "scanner.c"
yy51:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy88;
	case '|':	goto yy86;
	default:	goto yy52;
	}
yy52:
#line 219 "scanner.re"
	{ RET('|'); }
#line 592 "scanner.c"
yy53:
	++YYCURSOR;
#line 198 "scanner.re"
	{ RET(NEQ); }
#line 597 "scanner.c"
yy55:
	++YYCURSOR;
#line 199 "scanner.re"
	{ RET('{'); }
#line 602 "scanner.c"
yy57:
	++YYCURSOR;
#line 200 "scanner.re"
	{ RET('}'); }
#line 607 "scanner.c"
yy59:
	++YYCURSOR;
#line 201 "scanner.re"
	{ RET(','); }
#line 612 "scanner.c"
yy61:
	++YYCURSOR;
#line 202 "scanner.re"
	{ RET(':'); }
#line 617 "scanner.c"
yy63:
	++YYCURSOR;
#line 203 "scanner.re"
	{ RET('='); }
#line 622 "scanner.c"
yy65:
	++YYCURSOR;
#line 204 "scanner.re"
	{ RET('('); }
#line 627 "scanner.c"
yy67:
	++YYCURSOR;
#line 205 "scanner.re"
	{ RET(')'); }
#line 632 "scanner.c"
yy69:
	++YYCURSOR;
#line 206 "scanner.re"
	{ RET('['); }
#line 637 "scanner.c"
yy71:
	++YYCURSOR;
#line 207 "scanner.re"
	{ RET(']'); }
#line 642 "scanner.c"
yy73:
	++YYCURSOR;
#line 210 "scanner.re"
	{ RET('!'); }
#line 647 "scanner.c"
yy75:
	++YYCURSOR;
#line 220 "scanner.re"
	{ RET('$'); }
#line 652 "scanner.c"
yy77:
	++YYCURSOR;
#line 221 "scanner.re"
	{ RET('#'); }
#line 657 "scanner.c"
yy79:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy85;
yy80:
#line 223 "scanner.re"
	{ goto std; }
#line 665 "scanner.c"
yy81:
	++YYCURSOR;
#line 226 "scanner.re"
	{
        if(cursor == s->eof) RET(EOI);
        s->line++;
        s->pos = cursor;
        RET(EOL);
    }
#line 675 "scanner.c"
yy83:
	yych = *++YYCURSOR;
	goto yy36;
yy84:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy85:
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy84;
	default:	goto yy80;
	}
yy86:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy90;
	default:	goto yy87;
	}
yy87:
#line 194 "scanner.re"
	{ RET(XOR); }
#line 700 "scanner.c"
yy88:
	++YYCURSOR;
#line 187 "scanner.re"
	{ RET(OREQ); }
#line 705 "scanner.c"
yy90:
	++YYCURSOR;
#line 188 "scanner.re"
	{ RET(XOREQ); }
#line 710 "scanner.c"
yy92:
	++YYCURSOR;
#line 186 "scanner.re"
	{ RET(POWEQ); }
#line 715 "scanner.c"
yy94:
	++YYCURSOR;
#line 184 "scanner.re"
	{ RET(MODEQ); }
#line 720 "scanner.c"
yy96:
	++YYCURSOR;
#line 182 "scanner.re"
	{ RET(MULEQ); }
#line 725 "scanner.c"
yy98:
	++YYCURSOR;
#line 193 "scanner.re"
	{ RET(ARROW); }
#line 730 "scanner.c"
yy100:
	++YYCURSOR;
#line 192 "scanner.re"
	{ RET(DECR); }
#line 735 "scanner.c"
yy102:
	++YYCURSOR;
#line 181 "scanner.re"
	{ RET(SUBEQ); }
#line 740 "scanner.c"
yy104:
	++YYCURSOR;
#line 191 "scanner.re"
	{ RET(INCR); }
#line 745 "scanner.c"
yy106:
	++YYCURSOR;
#line 180 "scanner.re"
	{ RET(ADDEQ); }
#line 750 "scanner.c"
yy108:
	++YYCURSOR;
#line 197 "scanner.re"
	{ RET(NEQ); }
#line 755 "scanner.c"
yy110:
	++YYCURSOR;
#line 195 "scanner.re"
	{ RET(LEQ); }
#line 760 "scanner.c"
yy112:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy114;
	default:	goto yy113;
	}
yy113:
#line 190 "scanner.re"
	{ RET(LSHIFT); }
#line 770 "scanner.c"
yy114:
	++YYCURSOR;
#line 179 "scanner.re"
	{ RET(LSHIFTEQ); }
#line 775 "scanner.c"
yy116:
	++YYCURSOR;
#line 196 "scanner.re"
	{ RET(GEQ); }
#line 780 "scanner.c"
yy118:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy120;
	default:	goto yy119;
	}
yy119:
#line 189 "scanner.re"
	{ RET(RSHIFT); }
#line 790 "scanner.c"
yy120:
	++YYCURSOR;
#line 178 "scanner.re"
	{ RET(RSHIFTEQ); }
#line 795 "scanner.c"
yy122:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy123:
	switch (yych) {
	case '\n':	goto yy124;
	case '"':	goto yy125;
	default:	goto yy122;
	}
yy124:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy9;
	case 1: 	goto yy29;
	case 2: 	goto yy31;
	case 3: 	goto yy34;
	case 4: 	goto yy36;
	case 5: 	goto yy126;
	case 6: 	goto yy130;
	}
yy125:
	yyaccept = 5;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':	goto yy122;
	default:	goto yy126;
	}
yy126:
#line 175 "scanner.re"
	{ RET(STRINGCONST); }
#line 829 "scanner.c"
yy127:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy137;
	default:	goto yy124;
	}
yy128:
	yyaccept = 6;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy128;
	case 'E':
	case 'e':	goto yy131;
	case 'F':
	case 'f':	goto yy132;
	default:	goto yy130;
	}
yy130:
#line 171 "scanner.re"
	{ RET(DOUBLECONST); }
#line 861 "scanner.c"
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy134;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy135;
	default:	goto yy124;
	}
yy132:
	++YYCURSOR;
#line 172 "scanner.re"
	{ RET(FLOATCONST); }
#line 883 "scanner.c"
yy134:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy135;
	default:	goto yy124;
	}
yy135:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy135;
	case 'F':
	case 'f':	goto yy132;
	default:	goto yy130;
	}
yy137:
	++YYCURSOR;
#line 177 "scanner.re"
	{ RET(ELLIPSIS); }
#line 922 "scanner.c"
yy139:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy154;
	default:	goto yy153;
	}
yy140:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
yy141:
	switch (yych) {
	case '.':	goto yy139;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy140;
	case 'E':
	case 'e':	goto yy142;
	case 'Q':
	case 'q':	goto yy145;
	case 'U':
	case 'u':	goto yy143;
	default:	goto yy29;
	}
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy149;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy150;
	default:	goto yy124;
	}
yy143:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'Q':
	case 'q':	goto yy147;
	default:	goto yy144;
	}
yy144:
#line 167 "scanner.re"
	{ RET(UINTCONST); }
#line 984 "scanner.c"
yy145:
	++YYCURSOR;
#line 168 "scanner.re"
	{ RET(LONGINTCONST); }
#line 989 "scanner.c"
yy147:
	++YYCURSOR;
#line 169 "scanner.re"
	{ RET(ULONGINTCONST); }
#line 994 "scanner.c"
yy149:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy150;
	default:	goto yy124;
	}
yy150:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy150;
	case 'F':
	case 'f':	goto yy132;
	default:	goto yy130;
	}
yy152:
	yyaccept = 6;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
yy153:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy152;
	case 'E':
	case 'e':	goto yy158;
	case 'F':
	case 'f':	goto yy132;
	default:	goto yy130;
	}
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy155;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy156;
	default:	goto yy124;
	}
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy156;
	default:	goto yy124;
	}
yy156:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy156;
	case 'F':
	case 'f':	goto yy132;
	default:	goto yy130;
	}
yy158:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy159;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy160;
	default:	goto yy124;
	}
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy160;
	default:	goto yy124;
	}
yy160:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy160;
	case 'F':
	case 'f':	goto yy132;
	default:	goto yy130;
	}
yy162:
	++YYCURSOR;
#line 185 "scanner.re"
	{ RET(ANDEQ); }
#line 1158 "scanner.c"
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy165;
	default:	goto yy124;
	}
yy165:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy165;
	case 'Q':
	case 'q':	goto yy145;
	case 'U':
	case 'u':	goto yy143;
	default:	goto yy29;
	}
yy167:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy168:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy167;
	default:	goto yy27;
	}
yy169:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy170:
	switch (yych) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy7;
	}
yy171:
	yych = *++YYCURSOR;
	goto yy7;
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy173;
	default:	goto yy170;
	}
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy174;
	default:	goto yy170;
	}
yy174:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy175;
	default:	goto yy170;
	}
yy175:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy176;
	}
yy176:
#line 138 "scanner.re"
	{ RET(PRINT); }
#line 1460 "scanner.c"
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy190;
	default:	goto yy170;
	}
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy179;
	default:	goto yy170;
	}
yy179:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy180;
	default:	goto yy170;
	}
yy180:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy181;
	default:	goto yy170;
	}
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':
	case 'm':	goto yy182;
	default:	goto yy170;
	}
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':
	case 'p':	goto yy183;
	default:	goto yy170;
	}
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy184;
	default:	goto yy170;
	}
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy185;
	default:	goto yy170;
	}
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy186;
	default:	goto yy170;
	}
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy187;
	default:	goto yy170;
	}
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy188;
	default:	goto yy170;
	}
yy188:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy189;
	}
yy189:
#line 142 "scanner.re"
	{ RET(USECOMPONENT); }
#line 1611 "scanner.c"
yy190:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy191;
	default:	goto yy170;
	}
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy192;
	default:	goto yy170;
	}
yy192:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy193;
	}
yy193:
#line 130 "scanner.re"
	{ RET(UNTIL); }
#line 1699 "scanner.c"
yy194:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy200;
	default:	goto yy170;
	}
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy196;
	default:	goto yy170;
	}
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy197;
	default:	goto yy170;
	}
yy197:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy198;
	default:	goto yy170;
	}
yy198:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy199;
	}
yy199:
#line 126 "scanner.re"
	{ RET(WHILE); }
#line 1801 "scanner.c"
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy201;
	default:	goto yy170;
	}
yy201:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy202;
	default:	goto yy170;
	}
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy203;
	default:	goto yy170;
	}
yy203:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy204;
	default:	goto yy170;
	}
yy204:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy205;
	default:	goto yy170;
	}
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy206;
	default:	goto yy170;
	}
yy206:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy207;
	}
yy207:
#line 131 "scanner.re"
	{ RET(WAITUNTIL); }
#line 1917 "scanner.c"
yy208:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'W':
	case 'w':	goto yy210;
	case 'X':
	case 'x':	goto yy209;
	default:	goto yy170;
	}
yy209:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy212;
	default:	goto yy170;
	}
yy210:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy211;
	}
yy211:
#line 135 "scanner.re"
	{ RET(NEW); }
#line 2007 "scanner.c"
yy212:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy213;
	}
yy213:
#line 124 "scanner.re"
	{ RET(NEXT); }
#line 2081 "scanner.c"
yy214:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy215;
	default:	goto yy170;
	}
yy215:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy216;
	}
yy216:
#line 121 "scanner.re"
	{ RET(FOR); }
#line 2162 "scanner.c"
yy217:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy218;
	}
yy218:
#line 111 "scanner.re"
	{ RET(IF); }
#line 2236 "scanner.c"
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy244;
	default:	goto yy170;
	}
yy220:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy221;
	default:	goto yy170;
	}
yy221:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'U':
	case 'V':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 'u':
	case 'v':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	case 'I':
	case 'i':	goto yy223;
	case 'S':
	case 's':	goto yy224;
	case 'T':
	case 't':	goto yy225;
	case 'W':
	case 'w':	goto yy226;
	default:	goto yy222;
	}
yy222:
#line 133 "scanner.re"
	{ RET(END); }
#line 2324 "scanner.c"
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy242;
	default:	goto yy170;
	}
yy224:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy236;
	default:	goto yy170;
	}
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'Y':
	case 'y':	goto yy232;
	default:	goto yy170;
	}
yy226:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy227;
	default:	goto yy170;
	}
yy227:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy228;
	default:	goto yy170;
	}
yy228:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy229;
	default:	goto yy170;
	}
yy229:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy230;
	default:	goto yy170;
	}
yy230:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy231;
	}
yy231:
#line 127 "scanner.re"
	{ RET(ENDWHILE); }
#line 2447 "scanner.c"
yy232:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':
	case 'p':	goto yy233;
	default:	goto yy170;
	}
yy233:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy234;
	default:	goto yy170;
	}
yy234:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy235;
	}
yy235:
#line 103 "scanner.re"
	{ RET(ENDTYPE); }
#line 2535 "scanner.c"
yy236:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy237;
	default:	goto yy170;
	}
yy237:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy238;
	default:	goto yy170;
	}
yy238:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy239;
	default:	goto yy170;
	}
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy240;
	default:	goto yy170;
	}
yy240:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy241;
	}
yy241:
#line 119 "scanner.re"
	{ RET(ENDSELECT); }
#line 2637 "scanner.c"
yy242:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy243;
	}
yy243:
#line 114 "scanner.re"
	{ RET(ENDIF); }
#line 2711 "scanner.c"
yy244:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy245;
	default:	goto yy170;
	}
yy245:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy246;
	}
yy246:
#line 113 "scanner.re"
	{ RET(ELSE); }
#line 2792 "scanner.c"
yy247:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy254;
	default:	goto yy170;
	}
yy248:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy249;
	}
yy249:
#line 122 "scanner.re"
	{ RET(TO); }
#line 2873 "scanner.c"
yy250:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':
	case 'p':	goto yy251;
	default:	goto yy170;
	}
yy251:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy252;
	default:	goto yy170;
	}
yy252:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy253;
	}
yy253:
#line 102 "scanner.re"
	{ RET(TYPE); }
#line 2961 "scanner.c"
yy254:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy255;
	default:	goto yy170;
	}
yy255:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy256;
	}
yy256:
#line 112 "scanner.re"
	{ RET(THEN); }
#line 3042 "scanner.c"
yy257:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy266;
	case 'T':
	case 't':	goto yy265;
	default:	goto yy170;
	}
yy258:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy262;
	default:	goto yy170;
	}
yy259:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'B':
	case 'b':	goto yy260;
	default:	goto yy170;
	}
yy260:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy261;
	}
yy261:
#line 107 "scanner.re"
	{ RET(SUB); }
#line 3139 "scanner.c"
yy262:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':
	case 'p':	goto yy263;
	default:	goto yy170;
	}
yy263:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy264;
	}
yy264:
#line 123 "scanner.re"
	{ RET(STEP); }
#line 3220 "scanner.c"
yy265:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy271;
	default:	goto yy170;
	}
yy266:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy267;
	default:	goto yy170;
	}
yy267:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy268;
	default:	goto yy170;
	}
yy268:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy269;
	default:	goto yy170;
	}
yy269:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy270;
	}
yy270:
#line 116 "scanner.re"
	{ RET(SELECT); }
#line 3322 "scanner.c"
yy271:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy272;
	default:	goto yy170;
	}
yy272:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy273;
	}
yy273:
#line 100 "scanner.re"
	{ RET(SETID); }
#line 3403 "scanner.c"
yy274:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy287;
	default:	goto yy170;
	}
yy275:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy276;
	}
yy276:
#line 98 "scanner.re"
	{ RET(AS); }
#line 3484 "scanner.c"
yy277:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy278;
	default:	goto yy170;
	}
yy278:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy279;
	default:	goto yy170;
	}
yy279:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy280;
	default:	goto yy170;
	}
yy280:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy281;
	default:	goto yy170;
	}
yy281:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy282;
	default:	goto yy170;
	}
yy282:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy283;
	default:	goto yy170;
	}
yy283:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy284;
	default:	goto yy170;
	}
yy284:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy285;
	default:	goto yy170;
	}
yy285:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy286;
	}
yy286:
#line 101 "scanner.re"
	{ RET(AUTODEFINE); }
#line 3614 "scanner.c"
yy287:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy288;
	default:	goto yy170;
	}
yy288:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy289;
	default:	goto yy170;
	}
yy289:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy290;
	}
yy290:
#line 108 "scanner.re"
	{ RET(ALIAS); }
#line 3702 "scanner.c"
yy291:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy299;
	case 'F':
	case 'f':	goto yy297;
	case 'L':
	case 'l':	goto yy300;
	default:	goto yy170;
	}
yy292:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':
	case 'm':	goto yy295;
	default:	goto yy170;
	}
yy293:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy294;
	}
yy294:
#line 129 "scanner.re"
	{ RET(DO); }
#line 3794 "scanner.c"
yy295:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy296;
	}
yy296:
#line 97 "scanner.re"
	{ RET(DIM); }
#line 3868 "scanner.c"
yy297:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	case 'A':
	case 'a':	goto yy310;
	default:	goto yy298;
	}
yy298:
#line 96 "scanner.re"
	{ RET(DEF); }
#line 3942 "scanner.c"
yy299:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy305;
	default:	goto yy170;
	}
yy300:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy301;
	default:	goto yy170;
	}
yy301:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy302;
	default:	goto yy170;
	}
yy302:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy303;
	default:	goto yy170;
	}
yy303:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy304;
	}
yy304:
#line 136 "scanner.re"
	{ RET(DELETE); }
#line 4044 "scanner.c"
yy305:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy306;
	default:	goto yy170;
	}
yy306:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy307;
	default:	goto yy170;
	}
yy307:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy308;
	default:	goto yy170;
	}
yy308:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy309;
	}
yy309:
#line 106 "scanner.re"
	{ RET(DECLARE); }
#line 4139 "scanner.c"
yy310:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy311;
	default:	goto yy170;
	}
yy311:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy312;
	default:	goto yy170;
	}
yy312:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy313;
	default:	goto yy170;
	}
yy313:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy314;
	}
yy314:
#line 118 "scanner.re"
	{ RET(DEFAULT); }
#line 4234 "scanner.c"
yy315:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy321;
	case 'S':
	case 's':	goto yy322;
	default:	goto yy170;
	}
yy316:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy317;
	default:	goto yy170;
	}
yy317:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy318;
	default:	goto yy170;
	}
yy318:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy319;
	default:	goto yy170;
	}
yy319:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy320;
	}
yy320:
#line 99 "scanner.re"
	{ RET(CONST); }
#line 4338 "scanner.c"
yy321:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy325;
	default:	goto yy170;
	}
yy322:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy323;
	default:	goto yy170;
	}
yy323:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy324;
	}
yy324:
#line 117 "scanner.re"
	{ RET(CASE); }
#line 4426 "scanner.c"
yy325:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy326;
	}
yy326:
#line 94 "scanner.re"
	{ RET(CALL); }
#line 4500 "scanner.c"
yy327:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':
	case 'm':	goto yy328;
	default:	goto yy170;
	}
yy328:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':
	case 'p':	goto yy329;
	default:	goto yy170;
	}
yy329:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy330;
	}
yy330:
#line 92 "scanner.re"
	{ RET(JUMP); }
#line 4588 "scanner.c"
yy331:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy333;
	case 'T':
	case 't':	goto yy332;
	default:	goto yy170;
	}
yy332:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy337;
	default:	goto yy170;
	}
yy333:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy334;
	default:	goto yy170;
	}
yy334:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'B':
	case 'b':	goto yy335;
	default:	goto yy170;
	}
yy335:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy336;
	}
yy336:
#line 93 "scanner.re"
	{ RET(GOSUB); }
#line 4692 "scanner.c"
yy337:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy338;
	}
yy338:
#line 91 "scanner.re"
	{ RET(GOTO); }
#line 4766 "scanner.c"
yy339:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'B':
	case 'b':	goto yy345;
	default:	goto yy170;
	}
yy340:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy341;
	case 'T':
	case 't':	goto yy343;
	default:	goto yy170;
	}
yy341:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy342;
	}
yy342:
#line 104 "scanner.re"
	{ RET(LEN); }
#line 4856 "scanner.c"
yy343:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy344;
	}
yy344:
#line 140 "scanner.re"
	{ RET(LET); }
#line 4930 "scanner.c"
yy345:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy346;
	default:	goto yy170;
	}
yy346:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy347;
	default:	goto yy170;
	}
yy347:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy348;
	}
yy348:
#line 90 "scanner.re"
	{ RET(LABEL); }
#line 5018 "scanner.c"
yy349:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy350:
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy349;
	case '\n':	goto yy353;
	case '\'':
	case ';':	goto yy351;
	default:	goto yy124;
	}
yy351:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy353;
	default:	goto yy351;
	}
yy353:
	++YYCURSOR;
#line 83 "scanner.re"
	{
        if (cursor == s->eof) RET(EOI);
        s->line++;
        s->pos = cursor;
        goto std;
    }
#line 5051 "scanner.c"
yy355:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':
	case 'm':	goto yy356;
	case 'T':
	case 't':	goto yy358;
	default:	goto yy170;
	}
yy356:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy357;
	}
yy357:
#line 80 "scanner.re"
	{ goto linecomment; }
#line 5134 "scanner.c"
yy358:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy359;
	default:	goto yy170;
	}
yy359:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy360;
	default:	goto yy170;
	}
yy360:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy361;
	default:	goto yy170;
	}
yy361:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy171;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy169;
	default:	goto yy362;
	}
yy362:
#line 109 "scanner.re"
	{ RET(RETURN); }
#line 5229 "scanner.c"
yy363:
	++YYCURSOR;
#line 183 "scanner.re"
	{ RET(DIVEQ); }
#line 5234 "scanner.c"
yy365:
	++YYCURSOR;
#line 78 "scanner.re"
	{ goto comment; }
#line 5239 "scanner.c"
}
#line 239 "scanner.re"


linecomment:

#line 5246 "scanner.c"
{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy369;
	default:	goto yy371;
	}
yy369:
	++YYCURSOR;
#line 244 "scanner.re"
	{
        if (cursor == s->eof) RET(EOI);
        s->line++;
        s->pos = cursor;
        s->tok = cursor - 1;
        RET(EOL);
    }
#line 5265 "scanner.c"
yy371:
	++YYCURSOR;
#line 252 "scanner.re"
	{ goto linecomment; }
#line 5270 "scanner.c"
}
#line 253 "scanner.re"


comment:

#line 5277 "scanner.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy377;
	case '*':	goto yy375;
	default:	goto yy379;
	}
yy375:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '/':	goto yy380;
	default:	goto yy376;
	}
yy376:
#line 269 "scanner.re"
	{ goto comment; }
#line 5296 "scanner.c"
yy377:
	++YYCURSOR;
#line 259 "scanner.re"
	{
        if(cursor == s->eof) {
            printf("%s:%d:%d: warning: open block comment at end of file\n",
                s->filename, first_line, first_column);
            RET(EOI);
        }
        s->tok = s->pos = cursor;
        s->line++;
        goto comment;
    }
#line 5310 "scanner.c"
yy379:
	yych = *++YYCURSOR;
	goto yy376;
yy380:
	++YYCURSOR;
#line 257 "scanner.re"
	{ goto std; }
#line 5318 "scanner.c"
}
#line 270 "scanner.re"


retpoint:
    s->cur = cursor;
    if (loc) {
        loc->first_line = first_line;
        loc->num_lines = (unsigned short)(s->line - first_line);
        loc->first_column = first_column;
        loc->num_columns = (unsigned short)(s->cur - s->tok);
    }
    
    return tokenid;
}

Scanner *scanner_init(const char *fn) {
	FILE *file = fopen(fn, "r");
	Scanner *s;
    /*int fd = open(fn, O_RDONLY);*/
    
	/*if (fd < 0) {*/
    if (!file) {
        return NULL;
    }
    
    s = (Scanner *)malloc(sizeof(struct Scanner));
    memset(s, 0, sizeof(struct Scanner));
    /*s->fd = fd;*/
	s->file = file;
    s->line = 1;
    s->filename = fn;
    
    return s;
}

void scanner_deinit(Scanner *s) {
    /*close(s->fd);*/
	fclose(s->file);
    if (s->bot)
        free(s->bot);
    free(s);
}

Token *token_from_scanner(const Scanner *scanner, unsigned id,
        const SourceLocation *loc) {
    
    /* note: Token already contains space for the null terminator. */
    size_t textlen = (size_t)(scanner->cur - scanner->tok);
    Token *tok = (Token *)malloc(sizeof(struct Token) + textlen);
    tok->id = id;
    tok->loc = *loc;
    tok->next = 0;
    tok->child = 0;
    memcpy(tok->text, scanner->tok, textlen);
	tok->text[textlen] = 0;
    return tok;
}

Token *token_from_text(const char *text, unsigned id) {
    size_t textlen = (size_t)strlen(text);
    Token *tok = (Token *)malloc(sizeof(struct Token) + textlen);
    memset(tok, 0, sizeof(struct Token));
    tok->id = id;
    memcpy(tok->text, text, textlen + 1);
    return tok;
}

Token *token_free(Token *token) {
    Token *next = token->next, *child = token->child;
    free(token);
    if (child)
        token_free_all(child);
    return next;
}

void token_free_all(Token *token) {
    Token *next = token->next, *child = token->child;
    free(token);
    if (child)
        token_free_all(child);
    if (next)
        token_free_all(next);
}

